### ISSUE TITLE
GITHUB ISSUE to JIRA STORY TEST @0003

### ISSUE THREAD

**Issue by JamesAnthonyPino** [nasa/edsc-search-test-config-2#6]
This should appear in JIRA as a new Story.

**Comment by earthdata-tasktop** [comment]
(Comment from James Pino):

Approved in JIRA.

**Comment by JamesAnthonyPino** [comment]
Hello from GH.

**Comment by earthdata-tasktop** [comment]
(Comment from James Pino):

Submitting for test in JIRA.

**Comment by earthdata-tasktop** [comment]
(Comment from James Pino):

Passed in JIRA.

**Comment by earthdata-tasktop** [comment]
(Comment from James Pino):

Completed in JIRA.
